In [26]:
import pandas as pd
import sqlite3
def sql(query):
    return display(pd.read_sql(query, conn))

In [27]:
energy = pd.read_csv("energy_cleaned.csv")
temperature = pd.read_csv("temperature_cleaned.csv")

In [28]:
conn = sqlite3.connect("energy_analysis.db")

In [29]:
energy.to_sql("energy", conn, if_exists="replace", index=False)
temperature.to_sql("temperature", conn, if_exists="replace", index=False)

20740

In [30]:
query = "SELECT * FROM energy LIMIT 10"
result = pd.read_sql(query, conn)
display(result)

,Country,Energy Type,Year,Energy Consumption,Energy Production,GDP,Population,Energy Intensity Per Capita,Energy Intensity By GDP,CO2 Emission
0,Afghanistan,all_energy_types,1980-01-01,0.026583,0.072561,47.7571,13356.5,0.001990,0.000557,NaN
1,Afghanistan,coal,1980-01-01,0.002479,0.002355,47.7571,13356.5,0.000186,0.000052,NaN
2,Afghanistan,natural_gas,1980-01-01,0.002094,0.062820,47.7571,13356.5,0.000157,0.000044,NaN
3,Afghanistan,petroleum_n_other_liquids,1980-01-01,0.014624,0.000000,47.7571,13356.5,0.001095,0.000306,NaN
4,Afghanistan,renewables_n_other,1980-01-01,0.007386,0.007386,47.7571,13356.5,0.000553,0.000155,0.0
5,Albania,all_energy_types,1980-01-01,0.162982,0.155562,47.7571,2682.7,0.060753,0.003413,NaN
6,Albania,coal,1980-01-01,0.024317,0.013229,47.7571,2682.7,0.009064,0.000509,NaN
7,Albania,natural_gas,1980-01-01,0.010470,0.010470,47.7571,2682.7,0.003903,0.000219,NaN
8,Albania,petroleum_n_other_liquids,1980-01-01,0.099297,0.101540,47.7571,2682.7,0.037014,0.002079,NaN
9,Albania,renewables_n_other,1980-01-01,0.028897,0.030323,47.7571,2682.7,0.010772,0.000605,0.0

In [32]:
# Check current column names
print(energy.columns.tolist())

['Country', 'Energy Type', 'Year', 'Energy Consumption', 'Energy Production', 'GDP', 'Population', 'Energy Intensity Per Capita', 'Energy Intensity By GDP', 'CO2 Emission']

In [33]:
# Clean them
energy.columns = energy.columns.str.strip().str.replace(" ", "_").str.lower()

In [34]:
# Verify new names
print(energy.columns.tolist())

['country', 'energy_type', 'year', 'energy_consumption', 'energy_production', 'gdp', 'population', 'energy_intensity_per_capita', 'energy_intensity_by_gdp', 'co2_emission']

In [35]:
# Reload into SQL
energy.to_sql("energy", conn, if_exists="replace", index=False)

47640

In [39]:
sql("""
PRAGMA table_info(energy)
""")

   cid                         name  type  notnull dflt_value  pk
0    0                      country  TEXT        0       None   0
1    1                  energy_type  TEXT        0       None   0
2    2                         year  TEXT        0       None   0
3    3           energy_consumption  REAL        0       None   0
4    4            energy_production  REAL        0       None   0
5    5                          gdp  REAL        0       None   0
6    6                   population  REAL        0       None   0
7    7  energy_intensity_per_capita  REAL        0       None   0
8    8      energy_intensity_by_gdp  REAL        0       None   0
9    9                 co2_emission  REAL        0       None   0

In [40]:
sql("""
SELECT country, year, co2_emission
FROM energy
WHERE energy_type = 'coal'
ORDER BY co2_emission DESC
""")

                  country        year  co2_emission
0                   China  2014-01-01   9113.558191
1                   China  2013-01-01   8970.681630
2                   China  2015-01-01   8939.781470
3                   China  2016-01-01   8646.270696
4                   China  2019-01-01   8546.287450
...                   ...         ...           ...
9195      Former U.S.S.R.  2019-01-01           NaN
9196    Former Yugoslavia  2019-01-01           NaN
9197        Germany, East  2019-01-01           NaN
9198        Germany, West  2019-01-01           NaN
9199  Hawaiian Trade Zone  2019-01-01           NaN

[9200 rows x 3 columns]