In [147]:
# Import necessary libraries
import pandas as pd
import os

In [148]:
# Load the cleaned datasets
energy = pd.read_csv("energy_cleaned.csv")
temperature = pd.read_csv("cleaned_temperature.csv")

In [149]:
# Check current column names
print(energy.columns.tolist())

['country', 'energy_type', 'year', 'energy_consumption', 'energy_production', 'gdp', 'population', 'energy_intensity_per_capita', 'energy_intensity_by_gdp', 'co2_emission']

In [150]:
# Clean the column names in the energy dataset by replacing spaces with underscores and converting to lowercase
energy.columns = energy.columns.str.strip().str.replace(" ", "_").str.lower()

In [151]:
# Verify new names
print(energy.columns.tolist())

['country', 'energy_type', 'year', 'energy_consumption', 'energy_production', 'gdp', 'population', 'energy_intensity_per_capita', 'energy_intensity_by_gdp', 'co2_emission']

In [152]:
# Which countries have highest CO2 emissions?
energy[energy["energy_type"] == "all_energy_types"].groupby("country")["co2_emission"].mean().sort_values(ascending=False).head(10)

country
United States     5290.096649
China             5071.245114
Russia            1676.491372
Japan             1134.363443
India             1023.213320
Germany            858.767597
United Kingdom     554.522657
Canada             503.211736
South Korea        421.584474
Italy              406.354148
Name: co2_emission, dtype: float64

In [153]:
# How has global energy consumption changed over time?
energy[energy["energy_type"] == "all_energy_types"].groupby("year")["energy_consumption"].sum()

year
1980-01-01    294.161021
1981-01-01    291.550123
1982-01-01    290.247660
1983-01-01    293.164982
1984-01-01    303.269902
1985-01-01    308.774580
1986-01-01    314.006977
1987-01-01    322.533323
1988-01-01    333.576339
1989-01-01    339.868129
1990-01-01    343.193973
1991-01-01    346.944787
1992-01-01    352.657903
1993-01-01    355.676656
1994-01-01    359.514245
1995-01-01    369.268369
1996-01-01    378.963157
1997-01-01    380.054625
1998-01-01    382.169043
1999-01-01    389.568730
2000-01-01    402.221110
2001-01-01    405.026345
2002-01-01    413.696495
2003-01-01    428.217251
2004-01-01    450.371637
2005-01-01    465.023242
2006-01-01    479.904357
2007-01-01    492.923747
2008-01-01    499.571082
2009-01-01    494.860460
2010-01-01    526.551214
2011-01-01    540.293977
2012-01-01    551.391486
2013-01-01    560.882871
2014-01-01    565.918891
2015-01-01    567.113179
2016-01-01    571.941814
2017-01-01    583.982739
2018-01-01    597.515363
2019-01-01    600.825591
Name: energy_consumption, dtype: float64

In [154]:
# Check column names in both datasets to ensure they are clean and consistent
print("Energy columns:", energy.columns.tolist())
print("Temperature columns:", temperature.columns.tolist())

Energy columns: ['country', 'energy_type', 'year', 'energy_consumption', 'energy_production', 'gdp', 'population', 'energy_intensity_per_capita', 'energy_intensity_by_gdp', 'co2_emission']
Temperature columns: ['Country', 'Year', 'Annual_Mean', 'Five_Year_Smooth', 'Code']

In [155]:
# Clean the column names in the temperature dataset by replacing spaces with underscores and converting to lowercase
temperature.columns = temperature.columns.str.strip().str.replace(" ", "_").str.lower()

In [156]:
# Merge both datasets to see CO2 vs temperature relationship
merged = pd.merge(
    energy[energy["energy_type"] == "all_energy_types"],
    temperature,
    on=["country", "year"],
    how="inner"
)
merged[["country", "year", "co2_emission", "annual_mean"]].head()

       country        year  co2_emission  annual_mean
0  Afghanistan  1980-01-01           NaN        13.01
1      Albania  1980-01-01           NaN        10.97
2      Algeria  1980-01-01           NaN        22.94
3       Angola  1980-01-01           NaN        21.50
4    Argentina  1980-01-01           NaN        15.13

In [157]:
# applied a conditional filter to the merged dataset to isolate entries where the country is Afghanistan and CO₂ emission data is available (non-null). I then used .head(5) to display a sample of the first five rows for inspection.
result = merged[
    (merged["country"] == "Afghanistan") & 
    (merged["co2_emission"].notna())
].head(5)

display(result)

,country,energy_type,year,energy_consumption,energy_production,gdp,population,energy_intensity_per_capita,energy_intensity_by_gdp,co2_emission,annual_mean,five_year_smooth,code
148,Afghanistan,all_energy_types,1981-01-01,0.029949,0.092724,47.7571,13171.7,0.002274,0.000627,1.325965,13.06,12.87,AFG
296,Afghanistan,all_energy_types,1982-01-01,0.031898,0.095068,47.7571,12882.5,0.002476,0.000668,1.509628,12.01,12.86,AFG
444,Afghanistan,all_energy_types,1983-01-01,0.039022,0.099713,47.7571,12537.7,0.003112,0.000817,1.659605,12.91,12.82,AFG
592,Afghanistan,all_energy_types,1984-01-01,0.039202,0.099827,47.7571,12204.3,0.003212,0.000821,2.059605,12.50,12.78,AFG
740,Afghanistan,all_energy_types,1985-01-01,0.038275,0.120968,47.7571,11938.2,0.003206,0.000801,2.065436,13.03,12.76,AFG

In [158]:
merged["year"] = pd.to_datetime(merged["year"]).dt.year
display(merged.head())

,country,energy_type,year,energy_consumption,energy_production,gdp,population,energy_intensity_per_capita,energy_intensity_by_gdp,co2_emission,annual_mean,five_year_smooth,code
0,Afghanistan,all_energy_types,1980,0.026583,0.072561,47.7571,13356.50,0.001990,0.000557,NaN,13.01,12.84,AFG
1,Albania,all_energy_types,1980,0.162982,0.155562,47.7571,2682.70,0.060753,0.003413,NaN,10.97,11.46,ALB
2,Algeria,all_energy_types,1980,0.780695,2.803017,47.7571,19221.70,0.040615,0.016347,NaN,22.94,23.07,DZA
3,Angola,all_energy_types,1980,0.058366,0.335098,47.7571,8341.29,0.006997,0.001222,NaN,21.50,21.47,AGO
4,Argentina,all_energy_types,1980,1.713088,1.597946,453.8190,27951.93,0.061287,0.003775,NaN,15.13,15.02,ARG

In [159]:
# Check how many rows merged successfully
print(f"Merged rows: {len(merged)}")
print(f"Countries: {merged['country'].nunique()}")
print(f"Year range: {merged['year'].min()} - {merged['year'].max()}")

Merged rows: 5920
Countries: 148
Year range: 1980 - 2019

In [160]:
print(f"CO2 nulls: {merged['co2_emission'].isna().sum()}")

CO2 nulls: 424

In [161]:
test = pd.read_csv("merged_final.csv")
print(f"Rows: {len(test)}")
print(f"Countries: {test['country'].nunique()}")
print(f"China rows: {len(test[test['country'] == 'China'])}")
print(f"India rows: {len(test[test['country'] == 'India'])}")

Rows: 8760
Countries: 219
China rows: 40
India rows: 40

In [162]:
# # Read the cleaned energy dataset and replaced spaces with underscores and converted to lowercase for consistency 
energy = pd.read_csv("energy_cleaned.csv")
energy.columns = energy.columns.str.strip().str.replace(" ", "_").str.lower()

In [163]:
# Read the cleaned temperature dataset and replaced spaces with underscores and converted to lowercase for consistency with the energy dataset
temperature = pd.read_csv("cleaned_temperature.csv")
temperature.columns = temperature.columns.str.strip().str.replace(" ", "_").str.lower()

In [164]:
# Replace country names in the temperature dataset to match those in the energy dataset for a successful merge
# It also caused some problems in the visualizations I did on tableau, so I changed some of the names to be more consistent with what tableau recognizes
temperature["country"] = temperature["country"].replace({
    "Russian Federation": "Russia",
    "Korea, Rep.": "South Korea",
    "Korea-": "North Korea",
    "Iran, Islamic Rep.": "Iran",
    "Congo, Dem. Rep.": "Congo-Kinshasa",
    "Gambia,": "Gambia, The",
    "Guinea Bissau": "Guinea-Bissau",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Myanmar": "Burma",
    "Slovak Republic": "Slovakia",
    "Syrian Arab Republic": "Syria",
    "Timor Leste": "Timor-Leste",
    "Trinidad And Tobago": "Trinidad and Tobago",
    "Venezuela, Rb": "Venezuela",
    "Yemen, Rep.": "Yemen",
    "Bahamas,": "The Bahamas",
})

In [ ]:
# Verified the merge results to confirm China and India 
# are now present after country name standardization
print(f"Countries: {merged['country'].nunique()}")
print(f"China: {len(merged[merged['country'] == 'China'])} rows")
print(f"India: {len(merged[merged['country'] == 'India'])} rows")

Countries: 148
China: 0 rows
India: 0 rows

In [166]:
print(os.path.abspath("merged_final.csv"))

c:\Users\New\OneDrive\Documents\Energy\merged_final.csv

In [167]:
energy = energy[energy["country"] != "Former U.S.S.R."]

In [ ]:
# Filtered out historical and dissolved countries from the energy 
# dataset that no longer exist as sovereign nations, such as the 
# Former U.S.S.R. and Former Yugoslavia. These entries were removed 
# because they would cause mismatches during the merge with the 
# temperature dataset and create mapping errors in Tableau, 
# since these countries are not recognized in modern geographic datasets.
historical = [
    "Former U.S.S.R.",
    "Former Yugoslavia", 
    "Former Czechoslovakia",
    "Former Serbia and Montenegro",
    "Germany, East",
    "Germany, West",
    "Hawaiian Trade Zone",
    "Netherlands Antilles",
]

energy = energy[~energy["country"].isin(historical)]

In [ ]:
# Did the same thing here except filtered out non-country entities that are 
# not recognized in Tableau, such as
#  U.S. Territories and Wake Island, to ensure 
# that the dataset only contains valid countries
#  for accurate mapping and analysis in Tableau.
non_countries = [
    "U.S. Pacific Islands",
    "U.S. Territories",
    "Wake Island",
]

energy = energy[~energy["country"].isin(non_countries)]

In [ ]:
# Checked for alternate spellings of Saint Vincent and the 
# Grenadines to ensure it matches Tableau's recognized 
# country name format before replacing
print(energy[energy["country"].str.contains("vincent", case=False)]["country"].unique())

['Saint Vincent and the Grenadines']

In [ ]:
# Replace the name "Saint Vincent/Grenadines" with "Saint Vincent and the Grenadines" to ensure consistency with Tableau's country naming conventions, which is crucial for accurate visualizations and analysis in Tableau. This step helps to avoid issues where the dataset's country name does not match what Tableau recognizes, ensuring that all data for Saint Vincent and the Grenadines is correctly aggregated and displayed in visualizations.
energy["country"] = energy["country"].replace({
    "Saint Vincent/Grenadines": "Saint Vincent and the Grenadines"
})
print ("Replaced successfully")

Replaced successfully

In [ ]:
# Used a left join instead of inner join to retain all energy 
# records, even where temperature data may be missing, 
# preserving the full country and year coverage
merged = pd.merge(
    energy[energy["energy_type"] == "all_energy_types"],
    temperature,
    on=["country", "year"],
    how="left"
)

In [175]:
# Final check of countries remaining after all cleaning steps
print(f"Countries remaining: {energy['country'].nunique()}")

Countries remaining: 219

In [176]:
# Save final cleaned datasets
energy.to_csv("energy_cleaned.csv", index=False)
energy.to_csv("energy_breakdown_final.csv", index=False)
merged.to_csv("merged_final.csv", index=False)
print("Saved successfully")

Saved successfully